// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM1.Data;

#nullable disable

namespace ORM1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORM1.Models.RoomImage_BCS240051", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages_BCS240051");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "room1.jpg",
                            IsThumbnail = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "room2.jpg",
                            IsThumbnail = true,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "room3.jpg",
                            IsThumbnail = true,
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("ORM1.Models.RoomType_BCS240051", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes_BCS240051");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phòng giá rẻ",
                            Name = "Phòng thường"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Có điều hòa",
                            Name = "Phòng cao cấp"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Đầy đủ tiện nghi",
                            Name = "Phòng VIP"
                        });
                });

            modelBuilder.Entity("ORM1.Models.Room_BCS240051", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms_BCS240051");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 20.0,
                            Description = "Tầng 1",
                            IsAvailable = true,
                            Name = "P101",
                            Price = 2000000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 22.0,
                            Description = "Tầng 1",
                            IsAvailable = true,
                            Name = "P102",
                            Price = 2500000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Area = 30.0,
                            Description = "Tầng 2",
                            IsAvailable = true,
                            Name = "P201",
                            Price = 3500000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Area = 35.0,
                            Description = "Tầng 2",
                            IsAvailable = false,
                            Name = "P202",
                            Price = 4000000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Area = 50.0,
                            Description = "VIP",
                            IsAvailable = true,
                            Name = "VIP01",
                            Price = 6000000m,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("ORM1.Models.RoomImage_BCS240051", b =>
                {
                    b.HasOne("ORM1.Models.Room_BCS240051", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ORM1.Models.Room_BCS240051", b =>
                {
                    b.HasOne("ORM1.Models.RoomType_BCS240051", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ORM1.Models.RoomType_BCS240051", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ORM1.Models.Room_BCS240051", b =>
                {
                    b.Navigation("RoomImages");
                });
#pragma warning restore 612, 618
        }
    }
}
